volumes:
  instance_data:
  user_models:

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - instance_data:/app/instance
      - user_models:/app/userModels